### ISSUE TITLE
Payment Request Flow Change

### ISSUE THREAD

**Issue by ssantanuberaa** [ssantanuberaa/Vidhikarya-Main#13]
## Previous Flow
1. Lawyer will raise a **Payment Request**
1. Client will **Approve** the Payment Request
1. The amount will be added to the Agreement.

## New Flow
1. Lawyer will raise a **Payment Request**
1. The amount will be added to the Agreement

**Comment by ssantanuberaa** [comment]
This is Done in Local 
## Changed Files 
1. views/Pages/Vidhikarya/Client/PaymentHistory.blade.php

**Comment by bkmallik** [comment]
Checked in local

**Comment by bkmallik** [comment]
Successfully tested in live.
