### ISSUE TITLE
The title of the Lawyer PaymentHistory Page

### ISSUE THREAD

**Issue by ssantanuberaa** [ssantanuberaa/Vidhikarya-Main#14]
The title of the Lawyer PaymentHistory page is Dashboard. It should be "Payment History"

**Comment by ssantanuberaa** [comment]
Fixed.
# File Changed
1. views/Pages/Vidhikarya/Lawyer/PaymentHistory.blade.php

**Comment by bkmallik** [comment]
checked in local

**Comment by bkmallik** [comment]
Successfully tested in live.
