### ISSUE TITLE
Multiple attempt by Lawyer while Mark Complete

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#15]
![screenshot 38](https://user-images.githubusercontent.com/35287474/34815513-9dce3e48-f6d7-11e7-87e3-d966a3246718.png)

**Comment by ssantanuberaa** [comment]
This is Not a Bug. This happens when lawyer clicks multiple time on a button. We need to disable the button after first click.
## Changed Files 
1. public/js/dist/Lawyer.js

**Comment by bkmallik** [comment]
Checked in local

**Comment by bkmallik** [comment]
Successfully tested in live.
