### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by ssantanuberaa** [ssantanuberaa/Vidhikarya-Main#17]
Currently we have reset password through email. Change this through OTP verification. Don't Send Email Verification anymore

## Steps 
1. User clicks on the forget Password.
1. We ask for Email.
1. Send OTP to registered Number and show following message to the User along with the Number.
1. Validate.
1. If success then show Reset Window.
1. If fail then Show Error Message.

> An OTP has been sent to your registered number ***** 89 7. (Give Resend OTP message button. User cannot resend message within 30s of last sent OTP.)
> Please confirm the OTP to reset your Password.

> **Error Message ** The OTP given doesn't match. Please Retry(Recycle the flow to )

**Comment by ssantanuberaa** [comment]
As I cannot test sms in local development, we need to test this in Live. Waiting for mam's approval

**Comment by ssantanuberaa** [comment]
## File Changed 
1. views/Pages/Vidhikarya/Global/ForgetPassword.blade.php
1. app/Http/Controllers/Authentication.php

**Comment by bkmallik** [comment]
After reset password it is logging in an unknown client ID with same name of the person whose i have reset the password.

**Comment by ssantanuberaa** [comment]
In the flow, we are sending the email as well. The email contains the same OTP so that the user have both choice

**Comment by bkmallik** [comment]
Successfully tested in local.
