### ISSUE TITLE
Consulting the lawyer in free legal advice 

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#19]
![screenshot 42](https://user-images.githubusercontent.com/35287474/34861233-7859fe42-f789-11e7-8eaa-ddbaf751a8fb.png)

**Comment by bkmallik** [comment]
![screenshot 43](https://user-images.githubusercontent.com/35287474/34861276-b7a0f5c4-f789-11e7-9eb5-2ff85b945c0e.png)

**Comment by bkmallik** [comment]
Solved and checked in live.

**Comment by sangram9988** [comment]
done

**Comment by ssantanuberaa** [comment]
I couldn't find Sangram in the list to assign him.
