### ISSUE TITLE
Fault in Homepage When the website is left in another inactive tab for long time

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#21]
![screenshot 45](https://user-images.githubusercontent.com/35287474/34863286-944bbf0e-f794-11e7-8497-2e45495156bc.png)

After some moments if you return the same tab , then it will be shown.

**Comment by ssantanuberaa** [comment]
When the site is left in an inactive tab for long time and we come back to the website, there's a glitch on the slider (On the top of the page) for about 500ms. The hidden text and image appears that supposed to be visible on the next animation loop.

However, the glitch last only for about 500ms and then everything is fine. Debugging this minor issue is time consuming as we have to deal with a framework that the slider is using. I suppose this should be done later. Closing the issue right now.
