### ISSUE TITLE
Message of pending response of answer is not showing for few cases in ask-a-question page.

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#23]
![screenshot 49](https://user-images.githubusercontent.com/35287474/34871306-305d8bde-f7b3-11e7-9dd6-738f0b90026f.png)
![screenshot 50](https://user-images.githubusercontent.com/35287474/34871307-30a62e84-f7b3-11e7-9f08-92dae138fbbe.png)

**Comment by bkmallik** [comment]
successfully tested in local.

**Comment by ssantanuberaa** [comment]
This thread is fixed by @sangram9988
