### ISSUE TITLE
Rating of Lawyer is not working after the final payment by client.

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#26]

**Comment by ssantanuberaa** [comment]
Done
## File Changes 
1. Client/Timeline.blade.php
1. PaymentController.php
1. Client.js
1. PaymentSuccess.blade.php

**Comment by bkmallik** [comment]
successfully tested in local

**Comment by bkmallik** [comment]
Successfully tested in live.
