### ISSUE TITLE
Error in Loading Dashboard of some lawyer

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#29]
Some Lawyer did not gave their account details because of migration , the table does not have entries for their account details . So it is showing error while loading dashboard.

**Comment by ssantanuberaa** [comment]
The following command is commited -
> SET FOREIGN_KEY_CHECKS=0; 
> INSERT INTO `LawyerAccountDetails`(`id`) SELECT id FROM UserMaster WHERE UserMaster.id NOT IN( SELECT id FROM LawyerAccountDetails) AND UserMaster.isFinalRegistrationStepThreeComplete = 1;

**Comment by bkmallik** [comment]
solved
