### ISSUE TITLE
Case timeline UI adjustment for mobile view

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#4]

**Comment by ssantanuberaa** [comment]
As Mam suggested, the left section where __Case Information__ Section is, should be hidden in Mobile View. The top part is the __Note__ section and the below part is the __Case History__
> When There's No note in the __Note__ Section, the __Note__ Section will be empty and there's empty placeholder.
> Mobile view starts when the mobile width is less than 500px

**Comment by bkmallik** [comment]
Checked in local

**Comment by bkmallik** [comment]
Successfully tested in live.
