### ISSUE TITLE
Mail text box are very small in case of forgot password(Mobile view)

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#5]

**Comment by ssantanuberaa** [comment]
The Textbox is not small, rather the whole container is small in mobile view. The forgetPassword page need responsiveness.
### File Changed
1. views/pages/Vidhikarya/Global/ForgetPassword.blade.php

**Comment by bkmallik** [comment]
Checked in local

**Comment by bkmallik** [comment]
Successfully tested in live.
