### ISSUE TITLE
Case is not closing after doing payment

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#7]
![screenshot 33](https://user-images.githubusercontent.com/35287474/34768215-3ea771ee-f620-11e7-8dec-cda542819f04.png)

**Comment by ssantanuberaa** [comment]
Fixed the issue -
#### Changed Files 
1. app/Http/Controllers/PaymentController.php

**Comment by bkmallik** [comment]
Successfully tested

**Comment by bkmallik** [comment]
Successfully tested in live.
