### ISSUE TITLE
Unexpected lines at the bottom of Post-case.

### ISSUE THREAD

**Issue by bkmallik** [ssantanuberaa/Vidhikarya-Main#8]
Either remove it or change its UI

**Comment by bkmallik** [comment]
![screenshot 34](https://user-images.githubusercontent.com/35287474/34769577-32d418c8-f624-11e7-8d10-76c5f63df0f0.png)

**Comment by ssantanuberaa** [comment]
It is fixed Now.
#### Changed Files
1. Pages/Vidhikarya/Client/CaseForm.blade.php

**Comment by bkmallik** [comment]
Plz upload the file.

**Comment by bkmallik** [comment]
Successfully tested.

**Comment by bkmallik** [comment]
Successfully tested in live.
